---
# defaults file for jenkins
jenkins_url: 'http://localhost:8080'
jenkins_home: /var/lib/jenkins
jenkins_path: /usr/local/lib/jenkins
jekins_version: stable

jenkins_plugins:
  git:
    name: 'git'
  github:
    name: 'github'



jenkins_state: started
