---
# tasks file for common
# 
#
    - name : remove existing compose yml
      file: 
       path: "{{ nexus_download_dir }}/nexus3-docker-compose.yml"
       state: absent 

#    - name: Install dependencies
#      become: true
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items:
#        - docker
#        - docker-compose
#

    - name: Copy docker-compose.yml to {{ nexus_download_dir }}
      template: src=nexus3-docker-compose.yml dest={{ nexus_download_dir }}

    - name: Configure docker compose 
      replace:
        path: "{{ nexus_download_dir }}/nexus3-docker-compose.yml"
        regexp: 'NEXUS_PORT:8081'
        replace: '{{ nexus_port }}:8081'
        #state: present
    
    - name: Enable the Docker daemon in systemd
      become: true
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Start the Docker daemon
      become: true
      systemd:
        name: docker
        state: started
        masked: no

    - name: change file permission /var/run/docker.sock
      become: true
      command: chmod 666 /var/run/docker.sock
 
    - name: Run Docker-Compose and Up Nexus3 on Post {{ nexus-port }}
      command: docker-compose -f {{ nexus_download_dir }}/nexus3-docker-compose.yml up -d 

#    - name: Run docker-compose
#      docker_compose:
#        project_src: /tmp
#        files:
#          - nexus-docker-compose.yml
