---
# tasks file for common
# 
#
    - name : remove existing compose yml
      file: 
       path: /tmp/nexus3-docker-compose.yml
       state: absent 

#    - name: Install dependencies
#      become: true
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items:
#        - docker
#        - docker-compose
#

    - name: Copy docker-compose.yml to /tmp
      template: src=nexus3-docker-compose.yml dest=/tmp
    
    - name: Enable the Docker daemon in systemd
      become: true
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Start the Docker daemon
      become: true
      systemd:
        name: docker
        state: started
        masked: no

    - name: change file permission /var/run/docker.sock
      become: true
      command: chmod 666 /var/run/docker.sock
 
    - name: Test docker
      command: docker images

    - name: Run Docker-Compose and Up Nexus3 on Post 8084
      command: docker-compose -f /tmp/nexus3-docker-compose.yml up -d 

    - name: Test Docker Container is up
      command: docker ps

#    - name: Run docker-compose
#      docker_compose:
#        project_src: /tmp
#        files:
#          - nexus-docker-compose.yml
