---
# tasks file for common
#

- name : remove existing compose yml
  file:
    path: /tmp/nexus3-docker-compose.yml
    state: absent

- name: Copy docker-compose.yml to /tmp
  template: src=sonarqube-docker-compose.yml dest=/tmp

- name: DOCKER COMPOSE SONARQUBE LISTING PORT
  command: docker-compose -f /tmp/sonarqube-docker-compose.yml up -d
