---
- name: Install docker compose
  gather_facts: No
  hosts: localhost
  connection: local

  vars:
    service_account_email: " "
    credentials_file: " " 
    project_id: tcs-hackathon-group-5

  tasks:
    - name: post to con
      shell: "sudo curl -L https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
    - name: changeperm
      shell: "sudo chmod +x /usr/local/bin/docker-compose"
    - name: chk
      shell: "docker-compose --version"
