---
# tasks file for common
#
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: true

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: true

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: true

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: true
      notify: 
        - Start Docker service

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: post to con
      shell: "sudo curl -L https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"

    - name: changeperm
      shell: "sudo chmod +x /usr/local/bin/docker-compose"

    - name: chk
      shell: "docker-compose --version"
 
#    - name: Update docker daemon.jason for insecure repositories
#      become: true
#      blockinfile:  
#        path: /etc/docker/daemon.json
#        create: yes
#        block: |
#          {
#            "insecure-registries" : ["{{ var_nexus_instance }}"]
#          }
#      notify: 
#        - Start Docker service
#        - change sock permission

 #   - name: Wait for Docker to finish starting
 #     wait_for:
 #       sleep: 60
  
    - name: Change docker.sock permission
      become: true
      file:
        path: /var/run/docker.sock
        mode: 0666
#
#    - name: Initialize Docker Login for Jenkins
#      command: docker login -u {{ docker_login_nexus_user }} -p {{ docker_login_nexus_password }} {{ nexus3_repository }}
