# tasks file for jenkins
---
- name: Configure jenkins vars
  include_vars: main.yml
- name: Update the software package repository
  become: true
  yum:
    name: "*"
    update_cache: yes
- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - git
    - texlive-latex
    - wget
    - deltarpm
    - maven    
- name: Download jenkins repo
  become: true
  command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/{{ jenkins_version }}/jenkins.repo
- name: Import Jenkins CI key
  become: true
  rpm_key:
    key: https://pkg.jenkins.io/{{ jenkins_version  }}/jenkins.io.key
    state: present
- name: Install Jenkins
  become: true
  yum:
    name: "jenkins"
    state: present
- name: Allow port 8080
  become: true
  shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
- name: Start jenkins
  become: true
  service:
    name: jenkins
    state: "{{ jenkins_state }}"
- name: Enable Jenkins
  become: true
  systemd:
    name: jenkins
    enabled: true
- name: create jenkins-cli path
  become: true
  file:
    path: "{{ jenkins_path }}/"
    state: directory
- name: sleep 30 secs
  wait_for: timeout=30
  delegate_to: localhost
- name: Get Admin Password
  become: true
  become_method: sudo
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: result
- name: Print init Password
  become: true
  debug:
    var: result.stdout
- name: install jenkins cli
  become: true
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_path }}/jenkins-cli.jar"
  when: jenkins_state != "stopped"
#- name: Install plugins without a specific version
#  jenkins_plugin:
#    name: "{{ item.name }}"
#  register: my_jenkins_plugin_unversioned
#  with_dict: "{{ vars[jenkins_plugins] }}"
# name: install Jenkins plugins
#  shell: wget http://updates.jenkins-ci.org/latest/"{{ item }}".hpi
#  shell: chmod -R 777 *
#  shell: java -jar "{{ jenkins_path }}"/jenkins-cli.jar -s "{{ jenkins_url }}" -auth admin:admin install-plugin "{{ item }}" -deploy -restart
#  with_items: "{{ jenkins_plugins }}"
